### ISSUE TITLE
Errror on Installation

### ISSUE THREAD

**Issue by mattb2401** [bolav/fuse-sqlite#7]
Error while trying to instal
module.js:340
    throw err;
          ^
Error: Cannot find module 'hosted-git-info'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/fusepm/lib/install.js:4:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by bolav** [comment]
Duplicates https://github.com/bolav/fusepm/issues/2
